// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOLAQqJ3PS1tC5sb2TPUYqkmy841qwdII',
    appId: '1:345632090042:web:1c555ae376db6fd0e6df83',
    messagingSenderId: '345632090042',
    projectId: 'easyshopping-b5e35',
    authDomain: 'easyshopping-b5e35.firebaseapp.com',
    storageBucket: 'easyshopping-b5e35.appspot.com',
    measurementId: 'G-MD4RV0Y44G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWlYKN7gGnJqanC8dA1cJVlf0gbwUOhWo',
    appId: '1:345632090042:android:1ca34c82273a836ae6df83',
    messagingSenderId: '345632090042',
    projectId: 'easyshopping-b5e35',
    storageBucket: 'easyshopping-b5e35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr3g3tZ92p__uUmq-MOgnSt2xGOexXHVE',
    appId: '1:345632090042:ios:42115007b00dd4a4e6df83',
    messagingSenderId: '345632090042',
    projectId: 'easyshopping-b5e35',
    storageBucket: 'easyshopping-b5e35.appspot.com',
    iosBundleId: 'com.example.eComm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOLAQqJ3PS1tC5sb2TPUYqkmy841qwdII',
    appId: '1:345632090042:web:0d4f806de6b42170e6df83',
    messagingSenderId: '345632090042',
    projectId: 'easyshopping-b5e35',
    authDomain: 'easyshopping-b5e35.firebaseapp.com',
    storageBucket: 'easyshopping-b5e35.appspot.com',
    measurementId: 'G-460X0SQXGT',
  );
}
